Repository kelvinndmo/teziafrica-be, pull requests merged in 2021-05, with the labels that each got.

#17 Created Models for The Flow Builder
  flowbuilder/models.py
Labels: In Review, In Testing

#21 Crud Serializers The For Flow-builder
  .gitignore
  clients/models.py
  flowbuilder/migrations/0001_initial.py
  flowbuilder/models.py
  flowbuilder/serializers.py
  flowbuilder/urls.py
  flowbuilder/views.py
  teziafricabe/settings.py
  teziafricabe/urls.py
Labels: In Review

#23 Created Authentication & Knowledge Hub Models, Serializers and Views
  .env.sample
  .gitignore
  Makefile
  articles/__init__.py
  articles/admin.py
  articles/apps.py
  articles/migrations/__init__.py
  articles/models.py
  articles/serializers.py
  articles/tests.py
  articles/urls.py
  articles/views.py
  authentication/admin.py
  authentication/backends.py
  authentication/models.py
  authentication/serializers.py
  authentication/urls.py
  authentication/views.py
  requirements.txt
  teziafricabe/settings.py
Labels: Complete

#24 Optimized Flowbuilder Models, Serializers and Views
  clients/__init__.py
  clients/admin.py
  clients/apps.py
  clients/migrations/__init__.py
  clients/models.py
  clients/tests.py
  clients/views.py
  flowbuilder/admin.py
  flowbuilder/models.py
  flowbuilder/serializers.py
  flowbuilder/urls.py
  flowbuilder/views.py
Labels: Complete
